# default config.yml
port: 4711

# Determine whether locations are RELATIVE to the spawn point (serveur pi) or ABSOLUTE (windows)
location: ABSOLUTE

# Determine whether hit events are triggered by LEFT clicks, RIGHT clicks or BOTH
hitclick: LEFT